  
version: 2.1
orbs:
  go: circleci/go@1.3.0
jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "./pamobot-deploy-go.sh"
workflows:
  main:
    jobs:
      - build
      - deploy:
            requires:
              - build