name: Go

on:
  push:
    branches: [ golang ]
  pull_request:
    branches: [ golang ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "configs/.env"
        FILE_DATA: ${{ secrets.DOTENV }}
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "configs/sqlboiler.toml"
        FILE_DATA: ${{ secrets.SQL_BOILER }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
        
    - name: Install packages
      run: |
        go get github.com/volatiletech/sqlboiler/v4
        go get github.com/volatiletech/null/v8
        go get github.com/volatiletech/sqlboiler/v4/drivers/
    
    - name: Render models
      run: sqlboiler mysql --config configs/sqlboiler.toml
    
    - name: Build
      run: go build cmd/bot/bot.go

    - name: Test
      run: go test -v ./bot
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Docker registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nupamore/pamo_bot
        tag_with_ref: true
    
