name: Go

on:
  push:
    branches: [ golang ]
  pull_request:
    branches: [ golang ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
        
    - name: Secret configs
      shell: bash
      env:
        DOTENV: ${{ secrets.DOTENV }}
        SQLBOILER_TOML: ${{ secrets.SQLBOILER_TOML }}
      run: |
        cd configs
        echo "$DOTENV" > .env
        echo "$SQLBOILER_TOML" > sqlboiler.toml

    - name: Render models
      run: |
        go get github.com/volatiletech/sqlboiler/v4
        go get github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql
        sqlboiler mysql --config configs/sqlboiler.toml

    - name: Test
      run: go test -v cmd/bot/bot.go
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/app:latest
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
